#' Generate framework-derived cluster annotations
#'
#' Converts multidimensional Framework scores into a concise,
#' human-readable annotation for each analyzed macrophage cluster.
#'
#' Identity is intentionally excluded here. Macrophage identity is
#' established upstream by the independent macrophage detector.
#'
#' @param profile A cluster profile generated by analyze_macrophage_profile().
#' @param ontology Macrophage ontology data frame.
#'
#' @return A data frame containing the dominant Lineage program and
#' the top Functional State programs for each cluster.
#' @keywords internal

.generate_framework_annotations <- function(profile, ontology) {

  if (!is.list(profile) || is.null(profile$scores)) {
    stop("profile must contain a 'scores' matrix.")
  }

  if (!is.data.frame(ontology)) {
    stop("ontology must be a data frame.")
  }

  scores <- profile$scores

  lineage_programs <- unique(
    ontology$Program[ontology$Dimension == "Lineage"]
  )

  functional_programs <- unique(
    ontology$Program[ontology$Dimension == "Functional State"]
  )

  if (length(lineage_programs) == 0) {
    stop("Ontology must contain Lineage programs.")
  }

  if (length(functional_programs) == 0) {
    stop("Ontology must contain Functional State programs.")
  }

  clusters <- colnames(scores)

  annotations <- lapply(clusters, function(cluster) {

    cluster_scores <- scores[, cluster]

    # -----------------------------
    # Dominant Lineage
    # -----------------------------

    lineage_scores <- cluster_scores[
      intersect(lineage_programs, names(cluster_scores))
    ]

    if (length(lineage_scores) == 0) {
      lineage <- NA_character_
    } else {
      lineage <- names(lineage_scores)[
        which.max(lineage_scores)
      ]
    }

    # -----------------------------
    # Top Functional States
    # -----------------------------

    functional_scores <- cluster_scores[
      intersect(functional_programs, names(cluster_scores))
    ]

    functional_scores <- sort(
      functional_scores,
      decreasing = TRUE
    )

    if (length(functional_scores) == 0) {

      functional_1 <- NA_character_
      functional_2 <- NA_character_

    } else {

      top_functional <- names(
        functional_scores[
          seq_len(min(2, length(functional_scores)))
        ]
      )

      functional_1 <- top_functional[1]

      functional_2 <- if (length(top_functional) >= 2) {
        top_functional[2]
      } else {
        NA_character_
      }
    }

    # -----------------------------
    # Full annotation
    # -----------------------------

    components <- c(
      lineage,
      functional_1,
      functional_2
    )

    components <- components[
      !is.na(components) & nzchar(components)
    ]

    full_annotation <- paste(
      components,
      collapse = " | "
    )

    data.frame(
      Cluster = cluster,
      Lineage = lineage,
      Functional_State_1 = functional_1,
      Functional_State_2 = functional_2,
      Full_annotation = full_annotation,
      stringsAsFactors = FALSE
    )
  })

  annotations <- do.call(rbind, annotations)

  rownames(annotations) <- NULL

  annotations$Cluster <- factor(
    annotations$Cluster,
    levels = clusters
  )

  annotations <- annotations[
    order(annotations$Cluster),
    ,
    drop = FALSE
  ]

  annotations$Cluster <- as.character(
    annotations$Cluster
  )

  rownames(annotations) <- NULL

  return(annotations)
}
